namespace MobileBandSync.MSFTBandLib
{
    using MobileBandSync.MSFTBandLib.Facility;
    using System;
    using System.Runtime.InteropServices;

    internal static class DeviceCommands
    {
        internal const ushort IndexShift = 0;
        internal const ushort IndexBits = 7;
        internal const ushort IndexMask = 0x7f;
        internal const ushort TXShift = 7;
        internal const ushort TXBits = 1;
        internal const ushort TXMask = 0x80;
        internal const ushort CategoryShift = 8;
        internal const ushort CategoryBits = 8;
        internal const ushort CategoryMask = 0xff00;
        internal static ushort CargoCoreModuleGetVersion;
        internal static ushort CargoCoreModuleGetUniqueID;
        internal static ushort CargoCoreModuleWhoAmI;
        internal static ushort CargoCoreModuleGetLogVersion;
        internal static ushort CargoCoreModuleGetApiVersion;
        internal static ushort CargoCoreModuleSdkCheck;
        internal static ushort CargoTimeGetUtcTime;
        internal static ushort CargoTimeSetUtcTime;
        internal static ushort CargoTimeGetLocalTime;
        internal static ushort CargoTimeSetTimeZoneFile;
        internal static ushort CargoTimeZoneFileGetVersion;
        internal static ushort CargoLoggerGetChunkData;
        internal static ushort CargoLoggerEnableLogging;
        internal static ushort CargoLoggerDisableLogging;
        internal static ushort CargoLoggerGetChunkCounts;
        internal static ushort CargoLoggerFlush;
        internal static ushort CargoLoggerGetChunkRangeMetadata;
        internal static ushort CargoLoggerGetChunkRangeData;
        internal static ushort CargoLoggerDeleteChunkRange;
        internal static ushort CargoProfileGetDataApp;
        internal static ushort CargoProfileSetDataApp;
        internal static ushort CargoProfileGetDataFW;
        internal static ushort CargoProfileSetDataFW;
        internal static ushort CargoRemoteSubscriptionSubscribe;
        internal static ushort CargoRemoteSubscriptionUnsubscribe;
        internal static ushort CargoRemoteSubscriptionGetDataLength;
        internal static ushort CargoRemoteSubscriptionGetData;
        internal static ushort CargoRemoteSubscriptionSubscribeId;
        internal static ushort CargoRemoteSubscriptionUnsubscribeId;
        internal static ushort CargoNotification;
        internal static ushort CargoNotificationProtoBuf;
        internal static ushort CargoDynamicAppRegisterApp;
        internal static ushort CargoDynamicAppRemoveApp;
        internal static ushort CargoDynamicAppRegisterAppIcons;
        internal static ushort CargoDynamicAppSetAppTileIndex;
        internal static ushort CargoDynamicAppSetAppBadgeTileIndex;
        internal static ushort CargoDynamicAppSetAppNotificationTileIndex;
        internal static ushort CargoDynamicPageLayoutSet;
        internal static ushort CargoDynamicPageLayoutRemove;
        internal static ushort CargoDynamicPageLayoutGet;
        internal static ushort CargoInstalledAppListGet;
        internal static ushort CargoInstalledAppListSet;
        internal static ushort CargoInstalledAppListStartStripSyncStart;
        internal static ushort CargoInstalledAppListStartStripSyncEnd;
        internal static ushort CargoInstalledAppListGetDefaults;
        internal static ushort CargoInstalledAppListSetTile;
        internal static ushort CargoInstalledAppListGetTile;
        internal static ushort CargoInstalledAppListGetSettingsMask;
        internal static ushort CargoInstalledAppListSetSettingsMask;
        internal static ushort CargoInstalledAppListEnableSetting;
        internal static ushort CargoInstalledAppListDisableSetting;
        internal static ushort CargoInstalledAppListGetNoImages;
        internal static ushort CargoInstalledAppListGetDefaultsNoImages;
        internal static ushort CargoInstalledAppListGetMaxTileCount;
        internal static ushort CargoInstalledAppListGetMaxTileAllocatedCount;
        internal static ushort CargoSystemSettingsOobeCompleteClear;
        internal static ushort CargoSystemSettingsOobeCompleteSet;
        internal static ushort CargoSystemSettingsFactoryReset;
        internal static ushort CargoSystemSettingsGetTimeZone;
        internal static ushort CargoSystemSettingsSetTimeZone;
        internal static ushort CargoSystemSettingsSetEphemerisFile;
        internal static ushort CargoSystemSettingsGetMeTileImageID;
        internal static ushort CargoSystemSettingsOobeCompleteGet;
        internal static ushort CargoSystemSettingsEnableDemoMode;
        internal static ushort CargoSystemSettingsDisableDemoMode;
        internal static ushort CargoSRAMFWUpdateLoadData;
        internal static ushort CargoSRAMFWUpdateBootIntoUpdateMode;
        internal static ushort CargoSRAMFWUpdateValidateAssets;
        internal static ushort CargoEFlashRead;
        internal static ushort CargoGpsIsEnabled;
        internal static ushort CargoGpsEphemerisCoverageDates;
        internal static ushort CargoFireballUINavigateToScreen;
        internal static ushort CargoFireballUIClearMeTileImage;
        internal static ushort CargoFireballUISetSmsResponse;
        internal static ushort CargoFireballUIGetAllSmsResponse;
        internal static ushort CargoFireballUIReadMeTileImage;
        internal static ushort CargoFireballUIWriteMeTileImageWithID;
        internal static ushort CargoThemeColorSetFirstPartyTheme;
        internal static ushort CargoThemeColorGetFirstPartyTheme;
        internal static ushort CargoThemeColorSetCustomTheme;
        internal static ushort CargoThemeColorReset;
        internal static ushort CargoHapticPlayVibrationStream;
        internal static ushort CargoGoalTrackerSet;
        internal static ushort CargoFitnessPlansWriteFile;
        internal static ushort CargoGolfCourseFileWrite;
        internal static ushort CargoGolfCourseFileGetMaxSize;
        internal static ushort CargoOobeSetStage;
        internal static ushort CargoOobeGetStage;
        internal static ushort CargoOobeFinalize;
        internal static ushort CargoCortanaNotification;
        internal static ushort CargoCortanaStart;
        internal static ushort CargoCortanaStop;
        internal static ushort CargoCortanaCancel;
        internal static ushort CargoPersistedAppDataSetRunMetrics;
        internal static ushort CargoPersistedAppDataGetRunMetrics;
        internal static ushort CargoPersistedAppDataSetBikeMetrics;
        internal static ushort CargoPersistedAppDataGetBikeMetrics;
        internal static ushort CargoPersistedAppDataSetBikeSplitMult;
        internal static ushort CargoPersistedAppDataGetBikeSplitMult;
        internal static ushort CargoPersistedAppDataSetWorkoutActivities;
        internal static ushort CargoPersistedAppDataGetWorkoutActivities;
        internal static ushort CargoPersistedAppDataSetSleepNotification;
        internal static ushort CargoPersistedAppDataGetSleepNotification;
        internal static ushort CargoPersistedAppDataDisableSleepNotification;
        internal static ushort CargoPersistedAppDataSetLightExposureNotification;
        internal static ushort CargoPersistedAppDataGetLightExposureNotification;
        internal static ushort CargoPersistedAppDataDisableLightExposureNotification;
        internal static ushort CargoGetProductSerialNumber;
        internal static ushort CargoKeyboardCmd;
        internal static ushort CargoSubscriptionLoggerSubscribe;
        internal static ushort CargoSubscriptionLoggerUnsubscribe;
        internal static ushort CargoCrashDumpGetFileSize;
        internal static ushort CargoCrashDumpGetAndDeleteFile;
        internal static ushort CargoInstrumentationGetFileSize;
        internal static ushort CargoInstrumentationGetFile;
        internal static ushort CargoPersistedStatisticsRunGet;
        internal static ushort CargoPersistedStatisticsWorkoutGet;
        internal static ushort CargoPersistedStatisticsSleepGet;
        internal static ushort CargoPersistedStatisticsGuidedWorkoutGet;

        static DeviceCommands();
        internal static void LookupCommand(ushort commandId, out FacilityEnum category, out TX isTXCommand, out byte index);
        internal static ushort MakeCommand(FacilityEnum category, TX isTXCommand, byte index);
    }
}

